apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata: 
  name: workloads
  namespace: gotk-system
spec: 
  interval: 1m0s
  path: ./workloads
  prune: true
  sourceRef: 
    kind: GitRepository
    name: gotk-system
  timeout: 2m0s
